services:
    # default configuration for services in *this* file
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
    SweetSallyBe\Helpers\Service\Helper:
        public: true
#    SweetSallyBe\Helpers\Service\Mailchimp:
#        public: true
#    MailchimpMarketing\ApiClient:
#        public: true